### ISSUE TITLE
pocoo.utils.email doesn't work with python2.4

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments-migration-test#2]
(Original issue 10 created by None on 2006-02-26T20:56:39+00:00)

Currently pocoo.utils.email requires python2.5 to work correctly.

{{{
Traceback (most recent call last):
  File "<stdin>", line 1, in ?
  File "pocoo/utils/email.py", line 9, in ?
    from smtplib import SMTP, SMTPError
ImportError: cannot import name SMTPError
}}}

Reported by blackbird

**Comment by Anteru** [comment]
(Original issue was assigned to gbrandl)

(Original issue 10 last updated on 2007-01-25T17:39:13+00:00)

(Issue automaticaly closed due to status in Bitbucket: resolved)
